<?php

namespace Database\Seeders;

use App\Models\KpiMaster;
use Illuminate\Database\Seeder;

class KpiMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kpis = [
            // ================= 1. KPI GLOBAL TPST MEGILAN =================
            [
                'kode_kpi' => 'GLOB_KEBERSIHAN',
                'nama_kpi' => 'Kebersihan Area TPST',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'kebersihan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Tidak ada tumpukan sampah di area receiving dan conveyor (Persentase hari bersih)',
            ],
            [
                'kode_kpi' => 'GLOB_BAU',
                'nama_kpi' => 'Pengendalian Bau',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'lingkungan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Tidak ada bau mengganggu di area sekitar TPST (Indeks monitoring bau harian)',
            ],
            [
                'kode_kpi' => 'GLOB_TONASE',
                'nama_kpi' => 'Target Pengolahan Sampah',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'operasional',
                'metric_type' => 'positif',
                'default_target' => 20.00,
                'satuan' => 'ton/hari',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Tonase pengolahan sampah minimal 20 ton/hari',
            ],
            [
                'kode_kpi' => 'GLOB_TIPPING',
                'nama_kpi' => 'Pendapatan Tipping Fee Swasta',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'keuangan',
                'metric_type' => 'positif',
                'default_target' => 20000000.00,
                'satuan' => 'Rp/bulan',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Pendapatan tipping fee pelanggan swasta minimal Rp 20.000.000/bulan',
            ],
            [
                'kode_kpi' => 'GLOB_MESIN',
                'nama_kpi' => 'Keandalan Mesin (Zero Mesin Off)',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'mesin',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'availability',
                'deskripsi' => 'Kesiapan dan uptime mesin pengolahan utama tanpa breakdown',
            ],
            [
                'kode_kpi' => 'GLOB_STAKEHOLDER',
                'nama_kpi' => 'Kepuasan Stakeholder (Zero Complain)',
                'level' => 'global',
                'jabatan_target' => 'global',
                'kategori' => 'pelayanan',
                'metric_type' => 'negatif',
                'default_target' => 0.00,
                'satuan' => 'kasus',
                'bobot' => 10.00,
                'formula_type' => 'penalty',
                'deskripsi' => 'Zero complain dari DLH Kabupaten Lamongan dan penggerobak/tossa desa',
            ],

            // ================= 2. KPI BUDI SUCAHYO (SITE MANAGER) =================
            [
                'kode_kpi' => 'MGR_TONASE',
                'nama_kpi' => 'Pencapaian Target Tonase',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'operasional',
                'metric_type' => 'positif',
                'default_target' => 20.00,
                'satuan' => 'ton/hari',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Memastikan target tonase sampah masuk dan diolah minimal 20 ton per hari',
            ],
            [
                'kode_kpi' => 'MGR_KEBERSIHAN',
                'nama_kpi' => 'Kebersihan TPST (Zero Tumpukan)',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'kebersihan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Memastikan tidak ada tumpukan sampah terbuka yang terlantar',
            ],
            [
                'kode_kpi' => 'MGR_MESIN',
                'nama_kpi' => 'Kinerja Mesin (Zero Downtime)',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'mesin',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'availability',
                'deskripsi' => 'Kesiapan fasilitas conveyor, separator, RDF, baler & wheel loader',
            ],
            [
                'kode_kpi' => 'MGR_DLH',
                'nama_kpi' => 'Kepuasan DLH (Zero Complain)',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'pelayanan',
                'metric_type' => 'negatif',
                'default_target' => 0.00,
                'satuan' => 'kasus',
                'bobot' => 15.00,
                'formula_type' => 'penalty',
                'deskripsi' => 'Menjaga hubungan stakeholder DLH Lamongan tanpa keluhan',
            ],
            [
                'kode_kpi' => 'MGR_REVENUE',
                'nama_kpi' => 'Pendapatan Tipping Fee',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'keuangan',
                'metric_type' => 'positif',
                'default_target' => 20000000.00,
                'satuan' => 'Rp/bulan',
                'bobot' => 15.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Target pendapatan tipping fee komersial swasta Rp 20 juta/bulan',
            ],
            [
                'kode_kpi' => 'MGR_SDM',
                'nama_kpi' => 'Kinerja & Disiplin SDM',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'sdm',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 10.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Tingkat kehadiran, koordinasi pengurus harian, dan disiplin 12 pemilah',
            ],
            [
                'kode_kpi' => 'MGR_REPORT',
                'nama_kpi' => 'Laporan Manajemen Tepat Waktu',
                'level' => 'jabatan',
                'jabatan_target' => 'site_manager',
                'kategori' => 'administrasi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 10.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Penyusunan laporan evaluasi mingguan & bulanan secara tepat waktu',
            ],

            // ================= 3. KPI NITA (ADMIN, DATA & COMMERCIAL) =================
            [
                'kode_kpi' => 'NIT_AKURASI',
                'nama_kpi' => 'Akurasi Laporan Operasional',
                'level' => 'jabatan',
                'jabatan_target' => 'admin_commercial',
                'kategori' => 'administrasi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Validitas laporan tonase, RDF, residu, dan sinkronisasi pembukuan',
            ],
            [
                'kode_kpi' => 'NIT_INPUT',
                'nama_kpi' => 'Input Data Digital Harian',
                'level' => 'jabatan',
                'jabatan_target' => 'admin_commercial',
                'kategori' => 'administrasi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Kelengkapan dan ketepatan waktu input data ritase dan hasil produksi harian',
            ],
            [
                'kode_kpi' => 'NIT_TIPPING',
                'nama_kpi' => 'Tipping Fee Swasta Rp 20 Jt/Bln',
                'level' => 'jabatan',
                'jabatan_target' => 'admin_commercial',
                'kategori' => 'keuangan',
                'metric_type' => 'positif',
                'default_target' => 20000000.00,
                'satuan' => 'Rp/bulan',
                'bobot' => 30.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Realisasi penagihan dan pendapatan tipping fee dari pelanggan komersial swasta',
            ],
            [
                'kode_kpi' => 'NIT_ADMIN_PELANGGAN',
                'nama_kpi' => 'Kelengkapan Administrasi Pelanggan',
                'level' => 'jabatan',
                'jabatan_target' => 'admin_commercial',
                'kategori' => 'administrasi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Tertib invoice, verifikasi surat jalan/tiket timbangan, dan rekap piutang',
            ],
            [
                'kode_kpi' => 'NIT_ZERO_COMPLAIN',
                'nama_kpi' => 'Zero Complain Administrasi',
                'level' => 'jabatan',
                'jabatan_target' => 'admin_commercial',
                'kategori' => 'pelayanan',
                'metric_type' => 'negatif',
                'default_target' => 0.00,
                'satuan' => 'kasus',
                'bobot' => 15.00,
                'formula_type' => 'penalty',
                'deskripsi' => 'Tidak ada kekeliruan invoice atau komplain dari klien/DLH terkait penagihan',
            ],

            // ================= 4. KPI AGUNG (EQUIPMENT, LOGISTIK & RECEIVING) =================
            [
                'kode_kpi' => 'AGN_WHEEL_LOADER',
                'nama_kpi' => 'Kesiapan Wheel Loader (Ready to Operate)',
                'level' => 'jabatan',
                'jabatan_target' => 'equipment_logistik',
                'kategori' => 'mesin',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 25.00,
                'formula_type' => 'availability',
                'deskripsi' => 'Availability kesiapan operasional wheel loader untuk feeding material',
            ],
            [
                'kode_kpi' => 'AGN_LANCAR_RECEIVING',
                'nama_kpi' => 'Kelancaran Receiving Area',
                'level' => 'jabatan',
                'jabatan_target' => 'equipment_logistik',
                'kategori' => 'operasional',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Kelancaran antrean truk, proses unloading, dan nihil antrean macet',
            ],
            [
                'kode_kpi' => 'AGN_SUPPORT_TONASE',
                'nama_kpi' => 'Dukungan Target Tonase (20 Ton/Hari)',
                'level' => 'jabatan',
                'jabatan_target' => 'equipment_logistik',
                'kategori' => 'operasional',
                'metric_type' => 'positif',
                'default_target' => 20.00,
                'satuan' => 'ton/hari',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Kelancaran suplai sampah masuk menuju hopper pemrosesan',
            ],
            [
                'kode_kpi' => 'AGN_KEBERSIHAN_RECEIVING',
                'nama_kpi' => 'Kebersihan Area Receiving',
                'level' => 'jabatan',
                'jabatan_target' => 'equipment_logistik',
                'kategori' => 'kebersihan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Area timbangan dan unloading bersih dari ceceran sampah',
            ],
            [
                'kode_kpi' => 'AGN_SAFETY',
                'nama_kpi' => 'Safety Alat Berat (Zero Accident)',
                'level' => 'jabatan',
                'jabatan_target' => 'equipment_logistik',
                'kategori' => 'k3',
                'metric_type' => 'negatif',
                'default_target' => 0.00,
                'satuan' => 'kasus',
                'bobot' => 20.00,
                'formula_type' => 'penalty',
                'deskripsi' => 'Zero insiden atau kecelakaan operasional alat berat dan armada',
            ],

            // ================= 5. KPI ANA MARIA (OPERASIONAL & QC) =================
            [
                'kode_kpi' => 'ANA_KEBERSIHAN_TPST',
                'nama_kpi' => 'Kebersihan Area TPST (Zero Tumpukan)',
                'level' => 'jabatan',
                'jabatan_target' => 'operasional_qc',
                'kategori' => 'kebersihan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 25.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'PIC TPST Bersih dan Bebas Tumpukan Sampah',
            ],
            [
                'kode_kpi' => 'ANA_KONTROL_BAU',
                'nama_kpi' => 'Kontrol Bau Area TPST',
                'level' => 'jabatan',
                'jabatan_target' => 'operasional_qc',
                'kategori' => 'lingkungan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'PIC TPST Tidak Berbau melalui pengelolaan tumpukan dan sanitasi',
            ],
            [
                'kode_kpi' => 'ANA_PRODUKTIVITAS_PEMILAH',
                'nama_kpi' => 'Produktivitas Tenaga Pemilah',
                'level' => 'jabatan',
                'jabatan_target' => 'operasional_qc',
                'kategori' => 'sdm',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Pencapaian target tonase pilahan oleh 12 tenaga pemilah',
            ],
            [
                'kode_kpi' => 'ANA_KUALITAS_MATERIAL',
                'nama_kpi' => 'Kualitas Pilahan (Kontaminasi Rendah)',
                'level' => 'jabatan',
                'jabatan_target' => 'operasional_qc',
                'kategori' => 'kualitas',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 20.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Material bernilai tidak terbuang ke residu TPA dan bersih',
            ],
            [
                'kode_kpi' => 'ANA_PRODUKSI_RDF',
                'nama_kpi' => 'Produksi RDF Optimal',
                'level' => 'jabatan',
                'jabatan_target' => 'operasional_qc',
                'kategori' => 'produksi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Kesesuaian residu yang diolah menjadi RDF dan pencapaian tonase bal RDF',
            ],

            // ================= 6. KPI TENAGA PEMILAH =================
            [
                'kode_kpi' => 'PML_HASIL_PILAHAN',
                'nama_kpi' => 'Jumlah Hasil Pilahan (kg/minggu)',
                'level' => 'pemilah',
                'jabatan_target' => 'pemilah',
                'kategori' => 'produktivitas',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 40.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Pencapaian target bobot material terpilah per minggu',
            ],
            [
                'kode_kpi' => 'PML_NILAI_EKONOMI',
                'nama_kpi' => 'Nilai Ekonomi Material Recovery (Rp)',
                'level' => 'pemilah',
                'jabatan_target' => 'pemilah',
                'kategori' => 'ekonomi',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 25.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Peningkatan valuasi rupiah dari material yang berhasil disortir',
            ],
            [
                'kode_kpi' => 'PML_KUALITAS_SORTIR',
                'nama_kpi' => 'Kualitas Sortir (Material Bersih)',
                'level' => 'pemilah',
                'jabatan_target' => 'pemilah',
                'kategori' => 'kualitas',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 15.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Tingkat kebersihan sortir dan rendahnya kontaminasi',
            ],
            [
                'kode_kpi' => 'PML_KEBERSIHAN_AREA',
                'nama_kpi' => 'Kebersihan Area Kerja Conveyor',
                'level' => 'pemilah',
                'jabatan_target' => 'pemilah',
                'kategori' => 'kebersihan',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 10.00,
                'formula_type' => 'checklist',
                'deskripsi' => 'Sampah tidak tercecer di meja conveyor dan lorong kerja',
            ],
            [
                'kode_kpi' => 'PML_DISIPLIN_K3',
                'nama_kpi' => 'Disiplin Kehadiran & K3',
                'level' => 'pemilah',
                'jabatan_target' => 'pemilah',
                'kategori' => 'k3',
                'metric_type' => 'positif',
                'default_target' => 100.00,
                'satuan' => '%',
                'bobot' => 10.00,
                'formula_type' => 'ratio',
                'deskripsi' => 'Kepatuhan penggunaan APD (sarung tangan, masker) dan kehadiran kerja',
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiMaster::updateOrCreate(
                ['kode_kpi' => $kpi['kode_kpi']],
                $kpi
            );
        }
    }
}
